//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentItem
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int MaterialAssetsId { get; set; }
        public decimal Amount { get; set; }
        public decimal PriceForUnit { get; set; }
        public string AssetsName { get { return MaterialAsset.Name; } }


        public virtual Document Document { get; set; }
        public virtual MaterialAsset MaterialAsset { get; set; }
    }
}
