//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public int СontractorId { get; set; }
        public int DocumentId { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Document Document { get; set; }
    }
}
