//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int StatusId { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Deadline { get; set; }
        public int ThemeId { get; set; }
        public string Customer { get; set; }
        public int ExecutorId { get; set; }
        public int PriorityId { get; set; }
        public int СompanyId { get; set; }
        public string Creator { get; set; }
        public string Address { get; set; }
        public string Content { get; set; }
        public string StatusName { get { return Status.Name; } }
        public string ThemeName { get { return Theme.Name; } }
        public string ExecutorName { get { return Employee.FullName; } }
        public string PriorityName { get { return Priority.Name; } }
        public string CompanyName { get { return Company.Name; } }
        public string DocumentName { get { return Document.Name; } }

        public Nullable<int> DocumentId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Document Document { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
