//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        public int Id { get; set; }
        public int MaterialAssetsId { get; set; }
        public int MinAmount { get; set; }
        public int MaxAmount { get; set; }
    
        public virtual MaterialAsset MaterialAsset { get; set; }
    }
}
