//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int Id { get; set; }
        public int MaterialAssetsId { get; set; }
        public int WarehousesId { get; set; }
        public decimal Amount { get; set; }
        public decimal PriceForUnit { get; set; }
        public string AssetsName { get { return MaterialAsset.Name; } }
        public string AssetsNumber { get { return MaterialAsset.ItemNumber; } }
        public string WarehouseName { get { return Storage.Name; } }

        public virtual MaterialAsset MaterialAsset { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
